#!/bin/bash
#
# This is an sdm plugin for: rxapp
#
# The plugin is called three times: for Phase 0, Phase 1, and post-install.
#

function loadparams() {
    source $SDMPT/etc/sdm/sdm-readparams
}

# $1 is the phase: "0", "1", or "post-install"
# $2 is the argument list: arg1=val1|arg2=val2|arg3=val3| ...
#
# Main code for the Plugin
#
phase=$1
pfx="$(basename $0)"     #For messages
args="$2"
loadparams

if [ "$phase" == "0" ]
then
    #
    # In Phase 0 all references to directories in the image must be preceded by $SDMPT
    #
    logtoboth "* Plugin $pfx: Start Phase 0"

    logtoboth "* Plugin $pfx: Complete Phase 0"

elif [ "$phase" == "1" ]
then
    #
    # Phase 1 (in nspawn)
    #
    logtoboth "* Plugin $pfx: Start Phase 1"

    logtoboth "> Plugin $pfx: Install postcardscanner service"

    cd /home/pi
    git clone https://github.com/nzottmann/postcardscanner.git
    cd postcardscanner
    python3 -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
    sudo systemctl enable postcardscanner.service

    logtoboth "> Set 'camera_auto_detect=1' in /boot/config.txt"
    sed -i "s/camera_auto_detect=0/camera_auto_detect=1/" /boot/config.txt

    logtoboth "* Plugin $pfx: Complete Phase 1"
else
    #
    # Plugin Post-install edits
    #
    logtoboth "* Plugin $pfx: Start Phase post-install"

    logtoboth "* Plugin $pfx: Complete Phase post-install"
fi