name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
    - '*.md'

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        variant:
          - name: hubland
            postcardscanner_version: 1e9eedef2d3a250da1c32b3df60590489f86a25c
            hubbel_url: https://hubbel-hybrid-client.netlify.app
          - name: stadtwue
            postcardscanner_version: a60404e0146109c80400c3eaab1f613991db506e
            hubbel_url: https://hubbel.hubbel-mitmachen.de
    env:
      RPI_IMG_FOLDER: raspios_lite_armhf-2023-05-03
      RPI_IMG_NAME: 2023-05-03-raspios-bullseye-armhf-lite
      SDM_TAG: 'V9.5'

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetches the whole history including tags, needed for tagger

    - name: Git tag
      id: tagger
      run: |
        DESC=$(git describe --tags)
        ARTIFACT_BASENAME=hubbel-$DESC-${{ matrix.variant.name }}
        echo "gitdesc=$DESC" >> $GITHUB_OUTPUT
        echo "artifact_basename=$ARTIFACT_BASENAME" >> $GITHUB_OUTPUT
        echo $ARTIFACT_BASENAME

    - name: Install sdm
      run: |
        curl -L https://raw.githubusercontent.com/gitbls/sdm/$SDM_TAG/EZsdmInstaller -o EZsdmInstaller
        chmod 755 EZsdmInstaller
        sudo ./EZsdmInstaller

    - name: Fetch and unpack rpi os image
      run: |
        wget https://downloads.raspberrypi.org/raspios_lite_armhf/images/$RPI_IMG_FOLDER/$RPI_IMG_NAME.img.xz
        unxz $RPI_IMG_NAME.img.xz

    - name: Modify image with sdm
      run: |
        sed -i 's#HUBBEL_URL#${{ matrix.variant.hubbel_url }}#g' $PWD/files/.xinitrc
        chmod +x hubbel_plugin
        sudo sdm --customize \
          --plugin L10n:"keymap=de|locale=de_DE.UTF-8|timezone=Europe/Berlin"
          --restart \
          --plugin disables:"piwiz"
          --regen-ssh-host-keys \
          --user pi \
          --password-user raspberry \
          --autologin \
          --bootset camera=1,boot_behaviour=B2 \
          --extend --xmb 3072 \
          --bootscripts \
          --plugin apps:"apps=@hubbel_apps|name=hubbel_apps" \
          --plugin copyfile:"from=$PWD/files/.bash_profile|to=/home/pi|mkdirif=yes|chown=pi:pi|runphase=postinstall" \
          --plugin copyfile:"from=$PWD/files/.xinitrc|to=/home/pi|mkdirif=yes|chown=pi:pi|runphase=postinstall" \
          --plugin copyfile:"from=$PWD/files/050-hubbel.sh|to=/usr/local/sdm/1piboot/|mkdirif=yes|chown=root:root|chmod=755" \
          --plugin copyfile:"from=$PWD/files/postcardscanner.service|to=/etc/systemd/system|mkdirif=yes|chown=root:root" \
          --plugin ./hubbel_plugin:"postcardscanner_version=${{ matrix.variant.postcardscanner_version }}" \
          $RPI_IMG_NAME.img

    - name: Zip image
      run: |
        mv $RPI_IMG_NAME.img ${{ steps.tagger.outputs.artifact_basename }}.img
        zip ${{ steps.tagger.outputs.artifact_basename }}.img.zip ${{ steps.tagger.outputs.artifact_basename }}.img

    - name: Upload sdimg
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.tagger.outputs.artifact_basename }}
        path: |
          ${{ steps.tagger.outputs.artifact_basename }}.img.zip
        retention-days: 3

    - name: Get Changelog Entry
      id: changelog_reader
      uses: mindsers/changelog-reader-action@b97ce03a10d9bdbb07beb491c76a5a01d78cd3ef # v2.2.2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        version: ${{ github.ref_name }}
        path: CHANGELOG.md

    - name: Release
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body: ${{ steps.changelog_reader.outputs.changes }}
        files: |
          ${{ steps.tagger.outputs.artifact_basename }}.img.zip
