name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
    - '*.md'

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      RPI_IMG_FOLDER: raspios_lite_armhf-2023-05-03
      RPI_IMG_NAME: 2023-05-03-raspios-bullseye-armhf-lite
      SDM_BRANCH: 7ec49db85c5b7ddf94160abd16be52101c0d3d23

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install sdm
      run: |
        curl -L https://raw.githubusercontent.com/gitbls/sdm/$SDM_BRANCH/EZsdmInstaller | bash

    - name: Fetch and unpack rpi os image
      run: |
        wget https://downloads.raspberrypi.org/raspios_lite_armhf/images/$RPI_IMG_FOLDER/$RPI_IMG_NAME.img.xz
        unxz $RPI_IMG_NAME.img.xz

    - name: Modify image with sdm
      run: |
        chmod +x hubbel_plugin
        sudo sdm --customize \
          --locale de_DE.UTF-8 \
          --keymap de \
          --restart \
          --disable piwiz \
          --regen-ssh-host-keys \
          --user pi \
          --password-user raspberry \
          --autologin \
          --bootset camera=1,boot_behaviour=B2 \
          --extend --xmb 3072 \
          --plugin apps:"apps=@hubbel_apps|name=hubbel_apps" \
          --plugin copyfile:"from=./files/.bash_profile|to=/home/pi/.bash_profile"
          --plugin copyfile:"from=./files/.xinitrc|to=/home/pi/.xinitrc"
          $RPI_IMG_NAME.img

    - name: Upload sdimg and update artifact
      uses: actions/upload-artifact@v3
      with:
        name: image
        path: |
          ${{ env.RPI_IMG_NAME }}.img
        retention-days: 3
